//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Templates.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Templates.Cli.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error from the custom middleware. {0}.
        /// </summary>
        public static string BadReqInternalServerError {
            get {
                return ResourceManager.GetString("BadReqInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid generation json data.
        /// </summary>
        public static string BadReqInvalidGenJson {
            get {
                return ResourceManager.GetString("BadReqInvalidGenJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid generation path.
        /// </summary>
        public static string BadReqInvalidGenPath {
            get {
                return ResourceManager.GetString("BadReqInvalidGenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid language for this platform.
        /// </summary>
        public static string BadReqInvalidLanguage {
            get {
                return ResourceManager.GetString("BadReqInvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid package.
        /// </summary>
        public static string BadReqInvalidPackage {
            get {
                return ResourceManager.GetString("BadReqInvalidPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid path.
        /// </summary>
        public static string BadReqInvalidPath {
            get {
                return ResourceManager.GetString("BadReqInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid platform.
        /// </summary>
        public static string BadReqInvalidPlatform {
            get {
                return ResourceManager.GetString("BadReqInvalidPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project name.
        /// </summary>
        public static string BadReqInvalidProjectName {
            get {
                return ResourceManager.GetString("BadReqInvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid project type.
        /// </summary>
        public static string BadReqInvalidProjectType {
            get {
                return ResourceManager.GetString("BadReqInvalidProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a backend or frontend framework at the very least.
        /// </summary>
        public static string BadReqNoBackendOrFrontend {
            get {
                return ResourceManager.GetString("BadReqNoBackendOrFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first sync templates before calling this endpoint..
        /// </summary>
        public static string BadReqNotSynced {
            get {
                return ResourceManager.GetString("BadReqNotSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing Command: {0}.
        ///{1}.
        /// </summary>
        public static string ErrorExecutingCommand {
            get {
                return ResourceManager.GetString("ErrorExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating. {0}.
        /// </summary>
        public static string ErrorGenerating {
            get {
                return ResourceManager.GetString("ErrorGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing Command: {0}.
        ///{1}.
        /// </summary>
        public static string ErrorParsingCommand {
            get {
                return ResourceManager.GetString("ErrorParsingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error syncing templates. {0}.
        /// </summary>
        public static string ErrorSyncingTemplates {
            get {
                return ResourceManager.GetString("ErrorSyncingTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Command: {0}.
        /// </summary>
        public static string ReceivedCommand {
            get {
                return ResourceManager.GetString("ReceivedCommand", resourceCulture);
            }
        }
    }
}
